### ISSUE TITLE
Button not visible with Lavender theme

### ISSUE THREAD

**Issue by hankur** [exo-do/nodebb-plugin-ignore-users#18]
Could you please add support for Lavender theme? 

Screenshot (there is no button after username):
![image](https://cloud.githubusercontent.com/assets/10405384/18026333/947b9b8c-6c4b-11e6-80ed-22272cac2780.png)

Using NodeBB v1.1.2, Lavender v3.0.13 and ignore-users v1.1.10.

**Comment by jarey** [comment]
Will have a look at it as soon as possible.
I'm looking forward to build an administration page for the plugin to be able to select the theme in use or specify the element on the screen where the ignore icon ( it is probably going to be a dropdown in the future to incude in the same pont of the interface the ignore chat functionality) should be displayed.

Thanks for using the plugin, any feedback is really appreciated.

**Comment by jarey** [comment]
Closed by #19 e90bc71
- You will see the ignore/unignore icon on the topic list on lavender:

![image](https://cloud.githubusercontent.com/assets/5025224/18064633/88f763ea-6e30-11e6-96ec-6df6c275d85f.png)
- Also, you can ignore/unignore user posts, and ignore/unignore user for chats from their user page:

![image](https://cloud.githubusercontent.com/assets/5025224/18064674/b50ac4fe-6e30-11e6-8c8d-44b8abd07af0.png)
- From your user page you can see your list of ignored users for posts visibility and for chats and perform unignore operation on both functionalities:

![image](https://cloud.githubusercontent.com/assets/5025224/18064717/f3358bd8-6e30-11e6-874c-18dea8a5c200.png)

@Projekt4769 Version 1.1.11 of the plugin is updated on npmn and includes all of this changes. ;)

**Comment by hankur** [comment]
Good work!
