### ISSUE TITLE
Plugin not working in NodeBB 1.6

### ISSUE THREAD

**Issue by x1nf1** [exo-do/nodebb-plugin-ignore-users#30]
Hi
Thanks for the plugin, but It doesn't work with NodeBB 1.6 . Could you please make this plugin compatible with latest version of NodeBB ? It is so practical.

Thanks

**Comment by FaizanZahid** [comment]
Just tested, it is not working with node bb 1.7.5

can anyone please make it compatible?

**Comment by FaizanZahid** [comment]
Just tested again on latest node bb 1.8.1 , still not working.

a very useful plugin to have. i hope someone can make it compatible?
